[package]
name = "ulid"
version = "0.3.1"
authors = ["dylanhart <dylan96hart@gmail.com>"]
edition = "2018"

license = "MIT"
readme = "README.md"

description = "a Universally Unique Lexicographically Sortable Identifier implementation"
keywords = ["ulid", "uuid", "sortable", "identifier"]

repository = "https://github.com/dylanhart/ulid-rs"

[dependencies]
chrono = "0.4"
lazy_static = "1.2"
rand = "0.6"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false

[workspace]
members = ["cli"]
