[package]
name = "horned-owl"
version = "0.6.1-alpha.0"
authors = ["Phillip Lord <phillip.lord@russet.org.uk>"]
description = "Library and Command Line tools for OWL Ontologies"

repository = "https://github.com/phillord/horned-owl"

keywords = ["xml", "ontology", "OWL", "command"]
categories = ["command-line-utilities", "parsing",
              "rendering", "science", "data-structures"]

license = "LGPL-3.0"
edition = "2018"

[dependencies]
curie = "0.0.8"
clap = "2.31.2"
failure = "0.1.2"
enum_meta = "0.6.0"
quick-xml="0.12.4"
indexmap="1.0.2"

[dev-dependencies]
bencher = "0.1.4"
mktemp = "0.3.1"

[[bench]]
name = "horned"
harness = false
